Seminar_guest1=input("Enter your attending guest name")
Seminar_guest2=input("Enter your attending guest name")
Seminar_guest3=input("Enter your attending guest name")
Seminar_guest4=input("Enter your attending guest name")
Seminar_guests =input(seminar_guest1,seminar_guest2,seminar_guest3,seminar_guest4)
